// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Datastore is an autogenerated mock type for the Datastore type
type Datastore struct {
	mock.Mock
}

// CreateShortURL provides a mock function with given fields: id, url
func (_m *Datastore) CreateShortURL(id int64, url string) (string, error) {
	ret := _m.Called(id, url)

	var r0 string
	if rf, ok := ret.Get(0).(func(int64, string) string); ok {
		r0 = rf(id, url)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(id, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLongURL provides a mock function with given fields: url
func (_m *Datastore) GetLongURL(url string) (string, error) {
	ret := _m.Called(url)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
